- name: Notify | Set Dat
  set_fact:
    date: "{{ lookup('pipe', 'date +%d/%m/%Y@%H:%M') }}"

- name: Notify | MS Teams
  uri:
    url: "{{ teams_webhook }}"
    body: "{{ notify_body }}"
    body_format: json
    method: POST


