- name: Notify | Set Dat
  set_fact:
    date: "{{ lookup('pipe', 'date +%d/%m/%Y@%H:%M') }}"

#- name: Notify | MS Teams
#  uri:
#    url: "{{ teams_webhook }}"
#    method: POST
#    return_content: yes
#    body: "{{ notify_body }}"
#    body_format: json

- name: post curl
  ansible.builtin.shell:
    cmd: 'curl -H 'Content-Type: application/json' -d '{"text": "Hello World"}' https://eafit.webhook.office.com/webhookb2/45e521fd-8784-433f-b48b-26bcb1f874ef@99f7b55e-9cbe-467b-8143-919782918afb/IncomingWebhook/87b11ed007184f8bbf70c3169bb0e31c/8fc2fd82-68c3-430c-b298-af48e241a729'


